// Generated by CoffeeScript 1.7.1
var AngularTemplatesCompiler;

var fs = require('fs');

module.exports = AngularTemplatesCompiler = (function() {
  AngularTemplatesCompiler.prototype.brunchPlugin = true;

  AngularTemplatesCompiler.prototype.type = 'template';

  AngularTemplatesCompiler.prototype.extension = 'html';

  function AngularTemplatesCompiler(config) {
    var _ref, _ref1;
    this.module = ((_ref = config.plugins) != null ? (_ref1 = _ref.angular_templates) != null ? _ref1.module : void 0 : void 0) || 'templates';
    this.base = ((_ref = config.plugins) != null ? (_ref1 = _ref.angular_templates) != null ? _ref1.base : void 0 : void 0) || '';
  }

  AngularTemplatesCompiler.prototype.parseHtml = function(str) {
    return str.replace(/'/g, "\\'").replace(/\r?\n/g, '');
  };

  AngularTemplatesCompiler.prototype.compile = function(data, path, callback) {
    var html, url;
    html = this.parseHtml(data);
    url = path.replace(/\\/g, "/");
    url = url.replace(this.base,"");
    return callback(null, "(function() {\n    var module;\n\n    try {\n        // Get current templates module\n        module = angular.module('" + this.module + "');\n    } catch (error) {\n        // Or create a new one\n        module = angular.module('" + this.module + "', []);\n    }\n\n    module.run([\"$templateCache\", function($templateCache) {\n        $templateCache.put('" + url + "', '" + html + "');\n    }]);\n})();");
  };

  return AngularTemplatesCompiler;

})();
