// Generated by CoffeeScript 1.7.1
var AngularTemplatesCompiler, escape;

escape = require('js-string-escape');

module.exports = AngularTemplatesCompiler = (function() {
  AngularTemplatesCompiler.prototype.brunchPlugin = true;

  AngularTemplatesCompiler.prototype.type = 'template';

  AngularTemplatesCompiler.prototype.extension = 'html';

  AngularTemplatesCompiler.prototype._default_path_transform = function(path) {
    return path;
  };

  function AngularTemplatesCompiler(config) {
    var _ref, _ref1, _ref2, _ref3;
    this.module = ((_ref = config.plugins) != null ? (_ref1 = _ref.angular_templates) != null ? _ref1.module : void 0 : void 0) || 'templates';
    this.path_transform = ((_ref2 = config.plugins) != null ? (_ref3 = _ref2.angular_templates) != null ? _ref3.path_transform : void 0 : void 0) || this._default_path_transform;
  }

  AngularTemplatesCompiler.prototype.compile = function(data, path, callback) {
    var html, url;
    html = escape(data);
    url = this.path_transform(path.replace(/\\/g, "/"));
    return callback(null, "(function() {\n    var module;\n\n    try {\n        // Get current templates module\n        module = angular.module('" + this.module + "');\n    } catch (error) {\n        // Or create a new one\n        module = angular.module('" + this.module + "', []);\n    }\n\n    module.run([\"$templateCache\", function($templateCache) {\n        $templateCache.put('" + url + "', '" + html + "');\n    }]);\n})();");
  };

  return AngularTemplatesCompiler;

})();
